" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

set backspace=indent,eol,start " allow backspacing over everything in insert mode
set history=50                 " keep 50 lines of command line history
set ruler                      " show the cursor position all the time
set showcmd                    " display incomplete commands
set ch=2                       " Make command line two lines high, otherwise make errors are shortened.
set cc=81                      " ColorColumn - Highlights the width limit

syntax on
colorscheme vim-monokai-tasty

" Enable fzf?
set rtp+=~/.fzf

set nostartofline

" Better search
set incsearch               " show match for partly typed search command
set ignorecase              " Ignore case in search patterns
set smartcase               " Override 'ignorecase' if the search pattern
set hlsearch

set shiftwidth=2
set tabstop=2
set expandtab
set backupext=.bak
set noswapfile
set visualbell              " no beeping
set selectmode=mouse,key    " I want shift-arrows to work
set keymodel=startsel       " I want shift+arrows to work
set autoindent              " always set autoindenting on
set smartindent
set wrap
set list
set number
set nobackup
set showmatch

" Stuff from: http://danielmiessler.com/study/vim/
" or: https://github.com/danielmiessler/vim/blob/master/.vim/vimrc
" Don't use ESC
"inoremap jk <ESC>
" Sane leader key
"let mapleader = ","

"
" Stuff that I am trying out
"

" Triger `autoread` when files changes on disk
" https://unix.stackexchange.com/questions/149209/refresh-changed-content-of-file-opened-in-vim/383044#383044
" https://vi.stackexchange.com/questions/13692/prevent-focusgained-autocmd-running-in-command-line-editing-mode
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
" https://vi.stackexchange.com/questions/13091/autocmd-event-for-autoread
autocmd FileChangedShellPost *
  \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

" Remove trailing white spaces.
" Borrowed from: https://makandracards.com/makandra/11541-how-to-not-leave-trailing-whitespace-using-your-editor-or-git
autocmd BufWritePre * :%s/\s\+$//e

highlight CursorLine cterm=NONE ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE
set cursorline

" Ispired by: https://www.youtube.com/watch?v=XA2WjJbmmoM
" Finding files

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we do tab completion
set wildmenu

set autoread
